export const USER_EXIST_MESSAGE = 'Пользователь с таким email уже существует.'
export const INVALID_TOKEN_MESSAGE = 'При авторизации произошла ошибка. Переданный токен некорректен.'
export const USER_UPDATE_MESSAGE = 'При обновлении пользователя произошла ошибка'
export const USER_REGISTRATION_MESSAGE = 'При регистрации пользователя произошла ошибка'
export const TECHS = ['HTML', 'CSS', 'JS', 'React', 'Git', 'Express.js', 'mongoDB']
export const MORE_CARDS_WIDE_SCREEN = 3
export const MORE_CARDS_SMALL_SCREEN = 2
export const MAX_CARDS_WIDE_SCREEN = 12
export const MAX_CARDS_MEDIUM_SCREEN = 8
export const MAX_CARDS_SMALL_SCREEN = 5
export const WIDE_SCREEN = 1280
export const MEDIUM_SCREEN = 768
export const SHORTS_DURATION = 40